emcc `
    -std=c23 `
    -O0 `
    -g3 `
    -Wall `
    -Wextra `
    -Wpedantic `
    -sASSERTIONS=2 `
    -sSAFE_HEAP=1 `
    -sSTACK_OVERFLOW_CHECK=2 `
    -sSTACK_SIZE=4194304 `
    .\src\main.c `
    -o build/edi.js
